### ISSUE TITLE
SWIG director method error

### ISSUE THREAD

**Issue by fidgetingbits** [fidgetingbits/IDArling#12]
I kept getting these errors while loading a local idb file (outside of IDArling but with IDArling loaded):

```
Traceback (most recent call last):
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\core.py", line 157, in ev_auto_queue_empty
    core._plugin.logger.debug("Auto queue empty hook")
SystemError: PyEval_EvalFrameEx returned a result with an error set
Exception in ida_idp.IDP_Hooks dispatcher function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_auto_queue_empty'
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\core.py", line 157, in ev_auto_queue_empty
    core._plugin.logger.debug("Auto queue empty hook")
SystemError: PyEval_EvalFrameEx returned a result with an error set
Exception in ida_idp.IDP_Hooks dispatcher function: SWIG director method error. Error detected when calling 'IDP_Hooks.ev_auto_queue_empty'
OverflowError: Python int too large to convert to C long
```

I'm not sure if this is somehow related to me or idarling in general.

**Comment by saidelike** [comment]
I haven't seen it for a while so closing
