### ISSUE TITLE
Hexrays_Hooks str decode() error

### ISSUE THREAD

**Issue by fidgetingbits** [fidgetingbits/IDArling#16]
Observed this error while viewing a decompiled function

```
Exception in ida_hexrays.Hexrays_Hooks dispatcher function: SWIG director method error. Error detected when calling 'Hexrays_Hooks.func_printed'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_hexrays.py", line 20464, in func_printed
    def func_printed(self, *args): return self.callback(hxe_func_printed, *args)
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\hooks.py", line 534, in _hxe_callback
    self._func_ea
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\hooks.py", line 624, in _get_user_lvar_settings
    dct["lvvec"].append(HexRaysHooks._get_lvar_saved_info(lv))
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\hooks.py", line 644, in _get_lvar_saved_info
    "name": Event.decode(lv.name),
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\events.py", line 64, in decode
    return s.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
Exception in ida_hexrays.Hexrays_Hooks dispatcher function: SWIG director method error. Error detected when calling 'Hexrays_Hooks.func_printed'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_hexrays.py", line 20464, in func_printed
    def func_printed(self, *args): return self.callback(hxe_func_printed, *args)
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\hooks.py", line 534, in _hxe_callback
    self._func_ea
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\hooks.py", line 624, in _get_user_lvar_settings
    dct["lvvec"].append(HexRaysHooks._get_lvar_saved_info(lv))
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\hooks.py", line 644, in _get_lvar_saved_info
    "name": Event.decode(lv.name),
  File "C:/Users/edg/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\events.py", line 64, in decode
    return s.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by saidelike** [comment]
I saw that before fixing all the py3 errors and likely fixed it in https://github.com/fidgetingbits/IDArling/commit/88f680b17e18943fed8c4bd4941875ffa9c63271 so closing
