### ISSUE TITLE
Invalid user.ea when a user join a session

### ISSUE THREAD

**Issue by paulfariello-syn** [fidgetingbits/IDArling#35]
Running IDArling on d4e823a5a (current master) with a standalone server.

Alice join a session with no user, then she doesn't interact with IDA.
Bob join the same session, when the server tries to send the JoinSession of Alice to Bob the following stack trace occurs:

```
Traceback (most recent call last):
  File "IDArling/idarling/shared/sockets.py", line 302, in event
    self._dispatch()
  File "IDArling/idarling/shared/sockets.py", line 320, in _dispatch
    elif not self.recv_packet(packet):
  File "IDArling/idarling/shared/server.py", line 125, in recv_packet
    self._handlers[packet.__class__](packet)
  File "IDArling/idarling/shared/server.py", line 299, in _handle_join_session
    user.ea,
TypeError: __init__() missing 1 required positional argument: 'ea'

```

**Comment by saidelike** [comment]
I haven't tested the fix but is quite simple so should be safe
