### ISSUE TITLE
UserLvarSettingsEvent - uninitialized "lvvec" dict key

### ISSUE THREAD

**Issue by bootleg** [fidgetingbits/IDArling#38]
When re-opening idb, code from `event.py` tries to reload saved state from `lvar_settings`. The ley `lvvec` may not has been created yet and thus an exception is displayed to the user.

```
Traceback (most recent call last):
  File "C:/Users/X/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\network\client.py", line 63, in _call_event
    packet()
  File "C:/Users/X/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\events.py", line 1041, in __call__
    for lv in self.lvar_settings["lvvec"]:
KeyError: 'lvvec'
```

**Comment by saidelike** [comment]
From `hooks.py`, it is pretty clear in some cases, no `lvvec` key is saved before sending it to the server side :

```py
    @staticmethod
    def _get_user_lvar_settings(ea):
        dct = {}
        lvinf = ida_hexrays.lvar_uservec_t()
        if ida_hexrays.restore_user_lvar_settings(lvinf, ea):
            dct["lvvec"] = []
            for lv in lvinf.lvvec:
                dct["lvvec"].append(HexRaysHooks._get_lvar_saved_info(lv))
            if hasattr(lvinf, "sizes"):
                dct["sizes"] = list(lvinf.sizes)
            dct["lmaps"] = []
            it = ida_hexrays.lvar_mapping_begin(lvinf.lmaps)
            while it != ida_hexrays.lvar_mapping_end(lvinf.lmaps):
                key = ida_hexrays.lvar_mapping_first(it)
                key = HexRaysHooks._get_lvar_locator(key)
                val = ida_hexrays.lvar_mapping_second(it)
                val = HexRaysHooks._get_lvar_locator(val)
                dct["lmaps"].append((key, val))
                it = ida_hexrays.lvar_mapping_next(it)
            dct["stkoff_delta"] = lvinf.stkoff_delta
            dct["ulv_flags"] = lvinf.ulv_flags
        return dct
```
so it makes sense it is not found when trying to propagate it after re-opening a previous idb
