### ISSUE TITLE
struct.error: required argument is not an integer

### ISSUE THREAD

**Issue by saidelike** [fidgetingbits/IDArling#62]
```
[idarling][DEBUG] Sending packet: JoinSession(group=XXX, project=YYY, database=ZZZ, tick=0, name=User, color=40191, ea=65536, silent=True)
[idarling][DEBUG] Installing hooks
[idarling][ERROR] required argument is not an integer
Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\shared\packets.py", line 207, in _run_callback
    self._callback(self._callresult)
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\core.py", line 331, in databases_listed
    self.hook_all()
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\core.py", line 246, in hook_all
    self._plugin.core.update_local_types_map()
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\core\core.py", line 125, in update_local_types_map
    t = ImportLocalType(i)
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\shared\local_types.py", line 436, in ImportLocalType
    return LocalType(name, typ_type, typ_fields, typ_cmt, typ_fieldcmts, typ_sclass)
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\shared\local_types.py", line 121, in __init__
    self.parsedList = self.ParseTypeString(self.TypeString)
  File "C:/Users/User/AppData/Roaming/Hex-Rays/IDA Pro/plugins\idarling\shared\local_types.py", line 202, in ParseTypeString
    ordinal = decode_ordinal_string(struct.pack("B", ordinal_length) + b"#" + tp.read_string(ordinal_length - 2))
struct.error: required argument is not an integer
```

**Comment by saidelike** [comment]
Note that this happens for a tick=0 so is not related to replaying an action, but really about just opening the IDB and running idarling plugin.
