### ISSUE TITLE
IDArling server error

### ISSUE THREAD

**Issue by laqieer** [fidgetingbits/IDArling#85]
```
[idarling][WARNING] (10.92.0.26:49501) Invalid packet received: bytearray(b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x0e\xbce)X\xef\xd5q@\'i\xc6\xfc^\xbe\xa2\x1e\xc9\x98M\xe2\x95\xa80 Z\xf7@-\xfe\xa01 \xb8\x188\x1e{!\x87\x1e\xe5\x1b\xac{!\xb5s\x9b\t\xe3zr\x9f\xde\x17Y2\xb35\xee\xe2s\xcd#\x00$\x13\x02\x13\x03\x13\x01\xc0,\xc00\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0$\xc0(\xc0#\xc0\'\x00\x9f\x00\x9e\x00k\x00g\x00\xff\x01\x00\x01\x8f\x00\x00\x008\x006\x00\x003laqieer-idarling-server.japaneast.azurecontainer.io\x00\x0b\x00\x04\x03\x00\x01\x02\x00")
[idarling][ERROR] (10.92.0.26:49501) 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte
Traceback (most recent call last):
  File "/idarling/idarling/shared/sockets.py", line 194, in _notify_read
    dct = json.loads(line.decode("utf-8"))
                     ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 8: invalid start byte
[idarling][WARNING] (10.92.0.26:49501) Invalid packet received: bytearray(b'\x00\x0c\x00')
[idarling][ERROR] (10.92.0.26:49501) Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/idarling/idarling/shared/sockets.py", line 194, in _notify_read
    dct = json.loads(line.decode("utf-8"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[idarling][WARNING] (10.92.0.26:49501) Invalid packet received: bytearray(b'\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00*\x00(\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08')
[idarling][ERROR] (10.92.0.26:49501) Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/idarling/idarling/shared/sockets.py", line 194, in _notify_read
    dct = json.loads(line.decode("utf-8"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[idarling][WARNING] (10.92.0.26:49501) Invalid packet received: bytearray(b'\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x03\x03\x03\x01\x03\x02\x04\x02\x05\x02\x06\x02\x00+\x00\x05\x04\x03\x04\x03\x03\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 B\t\x1e@%')
[idarling][ERROR] (10.92.0.26:49501) Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/idarling/idarling/shared/sockets.py", line 194, in _notify_read
    dct = json.loads(line.decode("utf-8"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[idarling][WARNING] (10.92.0.26:49501) Invalid packet received: bytearray(b':\x8dc\x00\x19\xcdd\xe3\x85\xc0\xc5')
[idarling][ERROR] (10.92.0.26:49501) 'utf-8' codec can't decode byte 0x8d in position 1: invalid start byte
Traceback (most recent call last):
  File "/idarling/idarling/shared/sockets.py", line 194, in _notify_read
    dct = json.loads(line.decode("utf-8"))
                     ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 1: invalid start byte
```

**Comment by Magxm** [comment]
Can confirm this issue on "Open from Remote Server" from one user of the server.
Works from another (same server, same instance, same version of ida)
